const DATA = [
  {
    id: 0,
    title: "IPhone X",
    price: 600,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphonex.png",
  },
  {
    id: 1,
    title: "IPhone XS",
    price: 650,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphoneXS.png",
  },
  {
    id: 2,
    title: "IPhone XS Max",
    price: 700,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone-xs-max.png",
  },
  {
    id: 3,
    title: "IPhone 11",
    price: 750,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone11.png",
  },
  {
    id: 4,
    title: "IPhone 11 Pro Max",
    price: 800,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone11promax.png",
  },
  {
    id: 5,
    title: "IPhone 12 Mini",
    price: 850,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone12mini.png",
  },
  {
    id: 6,
    title: "IPhone 12",
    price: 900,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone12.png",
  },
  {
    id: 7,
    title: "IPhone 12 Pro",
    price: 950,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone12pro.png",
  },
  {
    id: 8,
    title: "IPhone 12 Pro Max",
    price: 1000,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone12promax.png",
  },

  {
    id: 9,
    title: "IPhone 13",
    price: 1050,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone 13.png",
  },
  {
    id: 10,
    title: "IPhone 13 Pro",
    price: 1100,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone 13 pro.png",
  },
  {
    id: 11,
    title: "IPhone 13 Pro Max",
    price: 1150,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone 13 pro max.png",
  },
  {
    id: 12,
    title: "IPhone 14",
    price: 1200,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone-14.png",
  },
  {
    id: 13,
    title: "IPhone 14 Pro",
    price: 1250,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone 14 pro.png",
  },
  {
    id: 14,
    title: "IPhone 14 Pro Max",
    price: 1300,
    desc: "Thông tin sản phẩm",
    img: "/assets/images/products/iphone_14_pro max.png",
  },
];

export default DATA;
